### ISSUE TITLE
Instalar o pkpgcounter no CentOS 6

### ISSUE THREAD

**Issue by dipedro** [valcir/ibquota#11]
Tentei yum install pkpgcounter, mas não deu em nada. Alguém dá uma luz?

**Comment by valcir** [comment]
Olá Pedro,

Segue procedimento para instalação na mão:
$ cd /tmp
$ wget http://www.pykota.com/software/pkpgcounter/download/tarballs/pkpgcounter-3.50.tar.gz
$ tar -zxf pkpgcounter-3.50.tar.gz
$ cd pkpgcounter-3.50
$ python setup.py install

Obs: Considerei que o python-dev está instalado em sua máquina.

Boa sorte e não esquece de dar um retorno pra ajudar outros usuários com o mesmo problema.
Um abraço,
Valcir

**Comment by dipedro** [comment]
Olá @valcir , muito obrigado pela resposta. Tenho certeza que seu procedimento dará certo. Já tinha resolvido e a única coisa que fiz diferente foi em vez de ir pelo wget, eu fui no site pykota.com e baixei logo o arquivo e extraí no windows e depois enviei pro servidor via filezilla :D
Em breve, pra ajudar a galera irei postar aqui minha configuração de LDAP no ibquota e um print de como está meu usuários criados no windows server.
