### ISSUE TITLE
Ajuda na configuração do sistema

### ISSUE THREAD

**Issue by renatoduartepinheiro** [valcir/ibquota#12]
Estou tendo dificuldades para fazer o sistema todo funcionar. Segui o passo a passo postado aqui no Github, mas no relatório de impressão, mostra 
![nao-ha-politica-de-impressao](https://user-images.githubusercontent.com/31906805/61065561-52de2900-a3da-11e9-93e2-771afd0bf67b.jpg)

Não entendi claramente onde o Samba entra. Até achei este material aqui na internet, 
[ibquota.pdf](https://github.com/valcir/ibquota/files/3382879/ibquota.pdf)
mas não passei do passo 4, embora o Cups esteja funcionando. Também não sei se essa documentação é oficial, já que não foi achada aqui no repositório.

A política de quotas é pra ser implementada numa instituição de ensino da rede federal. 
Meu cenário atual aqui é esse: Debian 9.9, configurado exclusivamente para trabalhar com as quotas, impressoras Ricoh SP 4510SF na mesma rede. Servidor com Samba4 como controlador de domínio em outra máquina (outro Debian), também na mesma rede.

Obrigado a quem puder ajudar.

**Comment by valcir** [comment]
Bom dia Renato,

Aparentemente não há política de impressão para a impressora "imp-adm-01", você criou a política via GG (Web)?
Outro detalhe é a identificação do "dono" do job ou seja do usuário logado na estação. Tente enviar o job de uma estação real ao invés da máquina local (localhost).

A documentação PDF é referente a versão 2, é antiga.

Um abraço,
Valcir

**Comment by renatoduartepinheiro** [comment]
Valcir, 
Estou retornando às configurações do IBQuota após uma viagem. Obrigado por responder.
Realmente não havia política para a impressora. Demorei para descobrir onde é feita a vinculação. Talvez, numa próxima atualização, fosse interessante colocar todos os cadastros no mesmo menu.

Ainda não consegui resolver. Notei que as impressões que eu mando pelo Cups aparecem como canceladas, como na imagem
![cups-cancelado](https://user-images.githubusercontent.com/31906805/61656095-54d7a000-ac96-11e9-97f2-45771c180988.jpg)

1. Na instalação da impressora, fiquei com dúvida qual dessas opções devo escolher
![Uploading qual-opcao-escolher.jpg…]()

1.1 Após instalação, usando o arquivo .ppd, a conexão ficou assim:
![conexao](https://user-images.githubusercontent.com/31906805/61656666-a6345f00-ac97-11e9-9747-282da64cd5ab.jpg)
 
2. Sobre a opção Cadastros > Usuários, quem são esses usuários? Seriam os usuários que podem imprimir? Se for isso, teria que cadastrar todos? E os usuários do LDAP, são usados onde?

Obrigado pela ajuda.

**Comment by valcir** [comment]
Oi Renato,

Boa dica, vou colocar os cadastros no mesmo menu.

Sim você precisa cadastrar todos os usuários que irão imprimir. Também terá que verificar há há política de impressão para o usuário em questão. No seu teste de impressão, por exemplo, o usuário (dono da impressão) é o "root". 
Caso você tenha os usuários em um Diretório, então não precisará criá-los no ibquota, basta apontar o servidor que o IBQUOTA irá fazer a consulta via LDAP.

Um abraço

**Comment by renatoduartepinheiro** [comment]
Valcir,
Estou quase conseguindo...
Está aparecendo "Usuário sem quota". Não sei como defino cota para usuário. As políticas e grupos foram definidos. A consulta à LDAP está sendo feita. O nome do dono da impressão aparece normalmente. 
![image](https://user-images.githubusercontent.com/31906805/63618170-cb332f00-c5c1-11e9-9a3a-e133d0049379.png)

No Cups aparece impressão cancelada.

Obrigado pela força.

**Comment by valcir** [comment]
Oi Renato,
Você tem política de impressão criada para a impressora "imp05"? Esta política deve estar com o grupo dos usuários (professor.pardal e pardal).
Desculpa a demora, me perdi nas mensagens...

**Comment by renatoduartepinheiro** [comment]
Sim, a política já havia sido criada. 
Quando você diz que a política deve estar com o grupo de usuários, seria o grupo de usuários do LDAP (Active Directory) ou o grupo criado no próprio IBQUOTA?
Depois de muito insistir, parei de tentar fazer funcionar com o LDAP. Cadastrei tudo localmente (SQL) e deu certo. 

Obrigado.

**Comment by valcir** [comment]
Olá Renato,
Se você está utilizando a base local (SQL) então o grupo configurado na Política de Impressão é o criado no IBQUOTA mesmo (SQL). 
Bom, vou encerrar este ticket, ok?!
Um abraço,
Valcir

**Comment by ClelsonRib** [comment]
Olá Valcir,
Antes de mais nada gostaria de elogiar seu trabalho, parabéns!!!
Estou com os sistemas CUPS e IBQUOTA3 instalados e funcionando, porém não imprime...
Aqui como minha impressora está instalada no cups
![image](https://github.com/valcir/ibquota/assets/146244286/028cfa78-8747-4b9f-9b03-3dd9af3d07e5)

A regra de quota está configurada certinho, contabiliza no relatório, porém não imprime na impressora
![image](https://github.com/valcir/ibquota/assets/146244286/5b409895-5b36-4d6f-b91a-bbf0268b58f6)

Já verifiquei tudo que poderia ser, mas não consegui fazer imprimir de fato. Onde estou errando?
Me ajude!!! rsrs
