### ISSUE TITLE
Não to conseguindo logar no ibquota3 (gg)

### ISSUE THREAD

**Issue by gladson25** [valcir/ibquota#13]
Não consigo logar no ibquota, colocando admin

**Comment by valcir** [comment]
Gladson,
Qual a mensagem de erro?
No primeiro acesso o GG irá direcionar você para alterar a senha do "admin", página "primeiro_acesso.php". Você chegou nesta parte?

**Comment by gladson25** [comment]
Informa (Erro ao tentar fazer o login. Por favor, tentar novamente!)

Teve um comando que não consegui fazer (sudo mysql -u root -p ***** ibquota3 < ibquota3.sql)

Acredito que seja por isso

**Comment by gladson25** [comment]
Consegui executar o comando porém persiste sem acesso. Não consigo passar da tela de login

**Comment by valcir** [comment]
Será que o php está com o módulo mysql ativado no servidor web?
Dá pra verificar com o phpinfo();

**Comment by gladson25** [comment]
gladson@sv01:~$ phpinfo();
bash: erro de sintaxe próximo ao token inesperado `;'

**Comment by valcir** [comment]
Bom dia Gladson,

Eu que não fui claro. O phpinfo() é uma função do PHP. Você tem que criar uma página php e abrir no navegador.
Um abraço

**Comment by valcir** [comment]
Vou encerrar o Ticket, mas fique a vontade para abrir outro.
