### ISSUE TITLE
Data e Hora nos relatórios

### ISSUE THREAD

**Issue by frozendesigner** [valcir/ibquota#14]
Olá, pessoal gostaria de deixar minha sugestão para próxima versão na parte de relatório, não aparece a data e nem a hora em que o arquivo foi impresso... E sobre o arquivamento de impressões...

![image](https://user-images.githubusercontent.com/2778104/63435504-67600900-c3fd-11e9-8de9-21403d77fc20.png)
Modificado
![image](https://user-images.githubusercontent.com/2778104/63449768-21b03a00-c417-11e9-8e61-371a3141e782.png)

**Comment by valcir** [comment]
Olá frozendesigner, Sua sugestão é boa. 
Teria como compartilhar o código?

**Comment by renatoduartepinheiro** [comment]
Complementando essa sugestão, colocar a data no formato brasileiro seria interessante. Em vez de 2019-08-21, seria 21/08/2019.

Para fazer essa mudança, coloquei a formatação diretamente no SELECT: 
 DATE_FORMAT(data_impressao, '%d/%m/%y')

**Comment by frozendesigner** [comment]
implementado.
![image](https://user-images.githubusercontent.com/2778104/64041194-4736f500-cb35-11e9-9390-7f60404150a0.png)

**Comment by valcir** [comment]
Olá Pessoal, Obrigado pela dica.
Foi implementado, estará na próxima versão.
Segue arquivo para quem desejar baixar com a sugestão:
https://github.com/valcir/ibquota/commits/master/gg/relatorios/impressoes.php
Um abraço,
Valcir
