### ISSUE TITLE
Erro na contagem da quantidade de cópias

### ISSUE THREAD

**Issue by renatoduartepinheiro** [valcir/ibquota#15]
Se é um arquivo de 3 páginas (uma prova, por exemplo) e o professor manda imprimir 35 cópias para toda a turma, o sistema contabiliza apenas as 3 páginas do arquivo e não 3x35, como deveria ser. Assim, o professor imprime as 105 cópias e só são descontadas 3 impressões da cota dele.
Alguma ideia de como resolver isso? 

No mais, o sistema tem funcionado muito bem. Só o fato de saber que há uma política de quotas, o professor já reavalia a necessidade de realmente imprimir.

Obrigado.

**Comment by valcir** [comment]
Oi Renato,

Uma sugestão solução rápida seria alterar o drive de impressão, pois o contador de páginas não está conseguindo identificar as cópias. 
Se possível, poderia enviar os arquivos d00XXX-001e o c00XXX ? Quero dar uma olhada pra ver se é facil corrigir o contador de páginas.
Um abraço,

**Comment by renatoduartepinheiro** [comment]
Qual seria o driver de impressão mais indicado? Onde encontro os arquivos d00XXX-001e o c00XXX?

**Comment by valcir** [comment]
A maioria das impressoras possuem mais de um Drive disponível no momento da instalação, geralmente com suporte PS ou PCL, tente alterar e testar.

O local dos arquivos especificados está no parâmetro "RequestRoot directory" do arquivo de configuração do CUPS. Local Default "/var/spool/cups". 
O XXX dos arquivos representa o número do job que deseja coletar os arquivos.

**Comment by renatoduartepinheiro** [comment]
"O local dos arquivos especificados está no parâmetro "RequestRoot directory" do arquivo de configuração do CUPS. Local Default "/var/spool/cups"."
---- Não achei esse arquivos relacionados no arquivo de configuração do Cups, mas os encontrei no diretório. Coloquei os arquivos compactados [neste link](http://191.252.103.170/cups.rar).
Sobre o driver da impressora, vou testar usando os dois arquivos disponibilizados no site https://www.openprinting.org/printer/Ricoh/Ricoh-SP_4510SF

**Comment by renatoduartepinheiro** [comment]
No Cups, usei o arquivo .ppd (PostScript). Nas estações, após remover todos os drivers anteriores (usando as "propriedades de servidor de impressão" do Windows, acessível depois de executar o comando _printui /s /t2_), instalei o driver também PostScript e deu certo. Contou certo agora. 
Muito obrigado pela ajuda.

**Comment by valcir** [comment]
Ótima notícia!
Vou encerrar o ticket...
Obrigado pelo retorno
