### ISSUE TITLE
Não consigo chegar na página de acesso ao GG, não abre.

### ISSUE THREAD

**Issue by nizopi** [valcir/ibquota#16]
Olá Valcir, tudo bem?

Realizei a instalação conforme o manual, mas não consigo abrir a página do GG, sempre dá página não encontrada.

Utilizei:

Debian 8, 9 e 10;
Apache2
PHP 5 e 7
CUPS 
MariaDB e MySQL

Mas mesmo assim não carrega a página quando acesso:

http://ip_servidor/gg

Resultado do comando de teste:
 
$ perl /usr/lib/cups/backend/ibquota3 --check

IBQUOTA VERSAO 3.2 - CUPS BACKEND
Print Accounting Software

Checagem dos parametros:
PATH_PYTHON = /usr/bin/python [OK]
Python is executable [OK]
PATH_PKPGCOUNTER = /usr/bin/pkpgcounter [OK]
Base de Dados: LOCAL SQL [OK]

Poderiam me ajudar por favor? Gostaria de implantar onde trabalho, mas não saio dessa parte.

Muito obrigado.

**Comment by nizopi** [comment]
Pessoal, lendo alguns comentários do Valcir, fui conferir o modulo do php5-mysql, que é o que estou usando agora, não estava instalado, após a instalação e restart no apache2, a página carregou, cadastrei a senha e deu certo, vou continuar os testes agora e qualquer dúvida posto aqui novamente.

Obrigado.

**Comment by valcir** [comment]
Olá Nizopi,
A falta do módulo PHP-MYSQL é motivo de muitos problemas.
Obrigado por compartilhar com a gente e boa sorte nos testes. Vou encerrar o ticket, mas fique a vontade para enviar novas dúvidas.
Um abraço,
Valcir
