### ISSUE TITLE
Manual de uso

### ISSUE THREAD

**Issue by elrafa-sg** [valcir/ibquota#4]
Olá, estou tentando utilizar o sistema porém não consegui adicionar no AD, poderia criar uma explicação de como fazer para ele reconhecer os usuários do AD. E como adicionar um usuário a uma determinada impressora e etc.

**Comment by valcir** [comment]
Olá,
O IBQUOTA acesso o AD via LDAP, no menu configurações você deve selecionar "BASE LDAP" e editar as informações de acesso do AD (Ex: endereço do servidor, etc).
Você não adiciona um usuário a um determinada impressora, você deve criar uma "Política de impressão" e associar o grupo (de usuários) e a impressora.

No momento está corrido, mas mais pra frente pretendo fazer um tutorial detalhado!

Um abraço,
Valcir

**Comment by fenads** [comment]
Boa noite Valcir! 
Tentei também realizar a integração com AD, porem na hora de realizar o teste ele fica travado e não aparece msg de erro. Usei o filtro padrão que está no Ibquota.

**Comment by valcir** [comment]
Boa noite fenads,
Veja se a versão 3.2 melhorou o acesso ao LDAP.
Eu testei o filtro no Windows Server 2012, o básico está funcionando. O filtro pode mudar se você está utilizando um "schema" diferente do padrão, por exemplo.
Um abraço,
Valcir

**Comment by dipedro** [comment]
![config ldap](https://user-images.githubusercontent.com/12878726/56153026-aaabf600-5f8b-11e9-874a-46581453d87e.PNG)
![config ad](https://user-images.githubusercontent.com/12878726/56153205-fced1700-5f8b-11e9-9740-cf78f0b3b51a.PNG)
@elrafa-sg @fenads 
Olha como ficou minhas configurações.

**Comment by valcir** [comment]
Alterei o "Success" pelo "Sucesso" no script test_ldap.php.

**Comment by renatoduartepinheiro** [comment]
> 
> 
> ![config ldap](https://user-images.githubusercontent.com/12878726/56153026-aaabf600-5f8b-11e9-874a-46581453d87e.PNG)
> ![config ad](https://user-images.githubusercontent.com/12878726/56153205-fced1700-5f8b-11e9-9740-cf78f0b3b51a.PNG)
> @elrafa-sg @fenads
> Olha como ficou minhas configurações.

Passando para agradecer.
Gastei muito tempo tentando fazer a configuração do LDAP. Estava colocando apenas "Administrator" no nome do usuário LDAP. Depois que li sua postagem, alterei para o DOMÍNIO\ADMINISTRATOR e funcionou na hora. 
Obrigado.

**Comment by valcir** [comment]
Muito bom @renatoduartepinheiro !
Obrigado
