### ISSUE TITLE
Erro ao tirar Grupo da Política

### ISSUE THREAD

**Issue by paulolins-ufpe** [valcir/ibquota#6]
Antes de mais nada parabéns, pela iniciativa,, baixei a versão do Virtual Box.

Na política de impressão ao tentar excluir o grupo, não acontece nada, aparece somente uma tela em branco.

Outra situação, foi ao adicionar uma impressora de rede no cups e pedir pra imprimir uma pagina de testes, a mesma não aparece no relatório de impressão. Vi a sequinte linha de comando, nos arquivos  README, ibquota3:socket://[IPImpressora], com esse código na conexão consegui fazer a impressora ser visualizada no relatório do ibquota juntamento com o usuário, porém, ela não encontra mais a impressora.
Ex: 
ibquota3:socket://172.0.0.1 (Não imprime, mas aparece no relatório do ibquota)
socket://172.0.0.1 (Imprime, mas não aparece no relatório).
Poderia me dar uma luz, sobre isso.

Obs: a impressora está em rede e não localmente.

**Comment by valcir** [comment]
Oi Paulo,
Você está certo, o arquivo politica_gp.php está com erro na linha 53. A sintaxe aparentemente está correta, dá impressão que é um caracter "especial" na instrução sql, sabe aqueles que aparecem em arquivos txt que são editados em Linux e em Windows? Vou fazer novos testes depois, agora nao ver aqui... Obrigado por reportar o problema.

Sobre o erro da URI da impressora não consegui identificar... vou testar tb!

Um abraço

**Comment by paulolins-ufpe** [comment]
Agradeço as resposta, mas até agora não funcionou com impressora em rede.
Pode ver o jobs do cups é diferente do ibquota3.
![erro - impressora em rede](https://user-images.githubusercontent.com/45341539/52375162-62c19d80-2a35-11e9-8c7f-fa56abe6287c.jpg)

**Comment by valcir** [comment]
Oi Paulo,

Pelo que estou vendo o IBQUOTA não conseguiu calcular o número de página (está indicando 0 [Zero]). Você poderia fazer um teste? Trocar o drive de impressão por outro, quem sabe o contador consiga calcular. Dê preferência por drive PCL ou PS.

**Comment by valcir** [comment]
Oi Paulo,

O erro que tinha na exclusão do Grupo da Política de Impressão foi corrigido, arquivo disponível aqui: https://github.com/valcir/ibquota/blob/master/gg/politicas/politica_gp.php

A SQL estava errada :(

Favor retornar após substituição do arquivo se deu sucesso!
Desculpa a demora!
E com relação à contagem de página? Deu certo?

Uma abraço,
Valcir

**Comment by paulolins-ufpe** [comment]
Boa noite, vou baixar o arquivo .php pra verificar, mas a respeito do impressão, realmente não funciona. O sistema entende toda vez que coloca URL: ibquota3:socket://[ipdaimpressora]/[nomeimpressora] como sendo impressora local, ao adicionar na máquina windows não imprime, só retirando. Já usei samba, mas até agora nada, no log do cups, informa impressora não encontrada.
Estou tentando implementar no trabalho, mas sem sucesso até o momento.

**Comment by valcir** [comment]
Oi Paulo,

Por gentileza, qual a saída do comando:
# /usr/lib/cups/backend/ibquota3 --check

e a configuração printers.conf?

grato,
Valcir

**Comment by valcir** [comment]
Oi Paulo,
Saiu a versão 3.2. Resolveu o problema da impressão não sair!
Aguardo seu retorno...

**Comment by valcir** [comment]
Paulo, Vou encerrar o ticket pois tive retorno de outros usuários que o problema foi resolvido. Qualquer coisa, pode abrir um novo.
Obrigado pela ajuda!
