### ISSUE TITLE
Política sem Impressora

### ISSUE THREAD

**Issue by dancka** [valcir/ibquota#7]
Bom dia.
Crio os usuários. Crio os grupos. Crios as políticas, porém na hora da edição para selecionara impressora nada a acontece. Ja tentei instalar a impressora por rede, pelo usb, mas nada de consegui selecionar a impressora para imprimir.
Analisando o aquivo php da política, me parece faltar código, na parte da impressora.
Poderia verificar?

Desde já agradeço.

**Comment by valcir** [comment]
Boa tarde Dancka,

No momento da atribuição da Impressora na Política de Impressão você deve inserir o nome da impressora diferenciando as letras MAIÚSCULAS das minúsculas. A solução é case-sensitiva. 
Futuramente pretendo fazer um "auto-scan" das impressoras configuradas no CUPS, mas estou apanhando das funções IPP no PHP :(
Em último caso, caso a página não esteja funcionando, você pode inserir o nome da impressora na tabela "politica_impressora" campo impressora, em último caso!
Dei uma olhada no código e aparentemente está certo, não tenho condições neste momento de fazer testes (estou longe do ambiente de produção) mas depois vou verificar com mais detalhes.

Obrigado por utilizar o IBQUOTA e reportar os erros...
Um abraço,
Valcir

**Comment by dancka** [comment]
Valcir, bom dia.
Obrigado pela resposta. Já tentei de todas as formas possíveis colocar o nome da impressora instalada no cups, mas não salva. Vou refazer a instalação do zero.

**Comment by valcir** [comment]
dancka, 
Então o php que adiciona a Impressora continua com problema. Eu não consegui identificar ou reproduzir o erro.
Qual distribuição vc está utilizando?

**Comment by dancka** [comment]
Estou fazendo testes em uma distribuição  Lubuntu. 
Estive vendo que há um campo não informado, o campo peso, so não observei a instrução sql para ver este campo é passado como null.
E sobre não sai nada na impressora mesmo mostrando que a impressão foi bem sucedida?

**Comment by valcir** [comment]
Olá,
Não conheço o Lubuntu, mas deve ser padrão Debian.
O lance do peso da impressão ainda não está ok, esta é uma necessidade sugerida pelos meus amigos do IFGW/Unicamp, mas não interfere no seu erro.
Sobre o job não sair e o ibquota constar que foi bem sucedido, vou analisar o código do pykota pra ver se há algum detalhe. Ele (Jerome Alet) tem muita experiência com backend do CUPS. 
Há outras pessoas entrando em contato e dizendo que estão com o mesmo problema que você, deve ser algum detalhe que está passando e não deve ser erro no seu ambiente, pode relaxar!

Enquanto não resolver este problema, não irei implementar nada no ibquota. Estou me dedicando apenas 90min por noite no projeto, por isto estou lento!

Obrigado pela paciência e ajuda,
Valcir

**Comment by dancka** [comment]
Bom dia.
Ok. A distro Lubuntu é uma versão light do Ubuntu que possui base débian.
Me desculpe olhar seu código, mas não é o campo peso que falta na instrução sql é o campo prioridade. insere o campo no statement, igual você fez com peso, que passa a salvar a impressora.
Quanto a não sair nada na impressora ficamos no aguardo.
Obrigado.

**Comment by valcir** [comment]
Olá,
Saiu a versão 3.2 com a referida correção.
Obrigado pela ajuda e paciência!
Aguardo seu retorno...

**Comment by dancka** [comment]
Bom dia.
Funcionou a impressão, só para adicionar a impressora que ainda não está funcionando.
Você olhou a instrução o sql que comentei?
Se você fizer um teste de erro do $insert_stmt ( $insert_stmt->errno) vai obter na saída a informação de que o campo 'prioridade' não foi informado.
No mais parabéns pelo trabalho.

**Comment by valcir** [comment]
Bom dia,
Que bom que a impressão funcionou, eu estava muito preocupado com este erro.

Sobre a falta do campo "prioridade" comi bola, mas acabei de atualizar. O campo "prioridade" está definido como "NOT NULL" , foi erro meu! Agora vai!

Obrigado pelo retorno!
