### ISSUE TITLE
Configuração do LDAP

### ISSUE THREAD

**Issue by elrafa-sg** [valcir/ibquota#8]
Sobre as dependências:

$ sudo apt-get install apache2 build-essential cups pkpgcounter mysql-server php libdbd-mysql-perl libnet-ldap-perl

e tentar configurar o uso do LDAP o sistema diz o módulo PHP LDAP não está instalado.

sugiro adicionar a lista de pacotes necessários o módulo em questão: php-ldap

**Comment by elrafa-sg** [comment]
No script: "gg/test_ldap.php"

na linha 20, é feita uma inclusão do arquivo 'includes/ldap.php'.
Esse arquivo não existe.

**Comment by valcir** [comment]
Olá,

a) Dependência "php-ldap" inserida na documentação.
b) Arquivo "includes/ldap.php" disponibilizado.

Grato!
