### ISSUE TITLE
Problema para impressão usando ibquota

### ISSUE THREAD

**Issue by fanti1** [valcir/ibquota#9]
Olá Valcir. Primeiramente queria agradecer pelo trabalho em cima do ibquota.
Estou atualmente fazendo uma atualização com um servidor de impressão, integrei com o IBQUOTA. Uso o CUPS. Adicionei uma impressora usando seu tutorial ibquota3:socket://IP-DA-IMPRESSORA, e quando tento imprimir uma página de teste, parece que o "pacote" chega no CUPS, mas não sai dele. Me retorna um erro no log assim: Returning IPP client-error-attributes-or-values-not-supported for Get-Jobs
Poderia me ajudar?

**Comment by gabrieldru** [comment]
Boa noite Valcir ! Também tenho um problema semelhante(de não imprimir), inclusive o cups não mostra nenhum erro no log, porém, no ibquota aparece essa mensagem "Nao ha politica de impressao para esta impressora". Cheguei a verificar as polícias do cups, mas não consegui descobrir solução até o momento.  Se também puder me ajudar. Muito obrigado pelo ibqota. Show demais !

**Comment by valcir** [comment]
Olá, 
Por você ter fechado o ticket, acho que você resolveu o problema, provavelmente com a atualização da versão 3.2. (apenas pra ficar documentado)

Obrigado pelo interesse no IBQUOTA!
Um abraço,
Valcir

**Comment by fanti1** [comment]
Boa tarde!
Eu vou ser sincero, foi uma "noobisse" minha mesmo. Eu não havia configurado a questão das quotas, grupos, e usuários da forma correta. Então essa foi a causa.
Agradeço o feedback, mais uma vez.
PS: Seria possível num futuro próximo a exibição de gráficos estilo pizza ou algum outro, estilo o antiguíssimo jasmine?

**Comment by valcir** [comment]
kkkk, obrigado pela sinceridade, acontece! 
Sobre os gráficos é possível sim. No momento estou direcionando energia no funcionamento correto da ferramenta, depois será a vez do visual para deixar bonito, com gráficos lindos :)

Você tem alguma sugestão de relatório? Abre um ticket detalhando o que você precisa, quem sabe uma alma caridosa agiliza a implementação!

Um abraço,
Valcir

**Comment by fanti1** [comment]
Valeu valcir. Irei abrir um ticket, obrigado como sempre. Só mais uma pequena pergunta...
Vi que tem como sincronizar com um AD. Só não vi se tem como fazer com que o IBQUOTA pegue todos os logins dos usuários (estilo nome.algumacoisa) e adicione por lá, ou eu tenho que fazer manualmente?

**Comment by valcir** [comment]
Fanti1, o IBQUOTA tem dois funcionamentos: 01) Base Local, usuários no sql, nesta opção você pode importar a base, mas não tem ferramenta pronta pra isto. 02) Base LDAP, neste caso os usuários estão no sistema de Diretório, que pode ser o AD, o ibquota consulta as permissões do usuário em tempo real (se ele está no grupo cadastrado na Política de Impressão, por exemplo).

**Comment by fanti1** [comment]
Valcir, conseguimos fazer o que queríamos... fizemos uma importação de arquivos .csv direto no SQL, pela conexão direta no LDAP não estava importando os usuários.
Mas deu tudo certo, obrigado.

**Comment by valcir** [comment]
Belezura!

**Comment by BernardoIFCE** [comment]
Bom dia Valdir, parabéns pelo belíssimo trabalho desempenhado com o IBquota. Queria tirar uma dúvida com você. Eu instalei tudo como dito na documentação, porém, na hora de imprimir tive problemas com o usuário que o sistema me reporta informando que não tem quota, mas ao tempo em que cadastro o usuário local da Windows, o sistema me permite imprimir. Se eu cadastrar um usuário tipo "Bernardo" determinar grupo, política de impressão, quota e tudo e peço para imprimir ele não me permite imprimir com este usuário. Onde devo está errando?
